G-Epitech/AFMY-Seminar

- .env.example
- README.md
- apps/back/Dockerfile
- apps/back/package.json
- apps/front/Dockerfile
- docker-compose.yml
- package.json
According to #7 issue, I hadded docker build
> SEM 6 - Setup docker

- apps/back/Dockerfile
- apps/back/src/app/app.module.ts
- apps/back/src/main.ts
- apps/front/Dockerfile
- docker-compose.yml
- package.json
We fixed the Docker integration error due to package @seminar/common dependency.
> SEM-11 - Fix Docker integration 

- apps/back/.env.example
- apps/back/package.json
- apps/back/src/app/app.module.ts
- apps/back/src/classes/legacy-api/legacy-api-error.ts
- apps/back/src/providers/legacy-api/legacy-api.module.ts
- apps/back/src/providers/legacy-api/legacy-api.service.ts
- apps/back/src/types/legacy-api/dtos/index.ts
- apps/back/src/types/legacy-api/endpoints.type.ts
- apps/back/src/types/legacy-api/response.type.ts
- apps/back/src/utils/http.ts
- package-lock.json
I added the `LegacyApiService` that allow us to directly request the legacy API of soul-connection.fr.
> SEM-18 - Add legacy API fetching system

- apps/front/package.json
- apps/front/src/app/customers/[id]/closet/page.tsx
- apps/front/src/app/customers/page.tsx
- apps/front/src/components/customers/closet/combination.tsx
- apps/front/src/components/customers/closet/items.tsx
- apps/front/src/components/ui/sheet.tsx
- package-lock.json
I added the closet page with all the clothe of a customer.
> SEM-43 - Closet page

- apps/back/src/modules/customers/customers.service.ts
- packages/common/src/dtos/customers/get-customers.dto.ts
- packages/common/src/types/customer.type.ts
I added two filters to restrict customers on their creation date
> SEM-51 Add date filters to customers route

- apps/back/src/modules/customers/customers.controller.ts
- apps/back/src/modules/employees/employees.controller.ts
- packages/common/src/dtos/employees/get-me.dto.ts
I updated `GET /customers`, `GET /customers/:id`, `PATCH /customers/:id`, `DELETE /customers/:id` and `GET /employee/me` so they now return the photo url instead of the base64 of the photo.
> SEM-48 Improve responses payloads by replacing photos by their link

- apps/back/src/modules/customers/customers-migration.service.ts
- apps/back/src/modules/customers/customers.controller.ts
- apps/back/src/modules/customers/customers.service.ts
- apps/back/src/providers/legacy-api/legacy-api-convertors.ts
- apps/back/src/types/legacy-api/clothe-type.type.ts
- apps/back/src/types/legacy-api/dtos/index.ts
I added migration of clothes when some requests are made on route `/customers/:id/clothes`.
> SEM-49 - Add clothes migrations

- apps/back/src/modules/customers/customers.controller.ts
- apps/back/src/modules/permissions/permissions.service.ts
I added restriction to all customers route so only their coach or a manager can access it.
> SEM-41 Restrict all user routes

- apps/back/src/modules/customers/customers.controller.ts
- apps/back/src/modules/customers/customers.service.ts
- packages/common/src/dtos/customers/get-customers.dto.ts
- packages/common/src/types/customer.type.ts
I fixed customers filters and IsDateString that was wrongly used.
> SEM-57 Fix customers filters

- apps/front/src/api/customers/clothes.ts
- apps/front/src/api/customers/index.ts
- apps/front/src/api/customers/list.ts
- apps/front/src/app/customers/[id]/closet/page.tsx
- apps/front/src/components/customers/closet/combination.tsx
- apps/front/src/components/customers/closet/items.tsx
- package-lock.json
I link the customer closet to his clothes pictures. This will allow the coach to try some outfits.
> SEM-58 - link customer clothes

- apps/back/Dockerfile
- apps/front/Dockerfile
According to Linear isse #92, I updated the Dockerfile images to use the `package-lock.json` file and improve image build time.
> SEM-60 - Improve Dockerfiles

- apps/back/src/app/app.module.ts
- apps/back/src/modules/auth/auth.module.ts
- apps/back/src/modules/customers/customers-migration.service.ts
- apps/back/src/modules/customers/customers.controller.ts
- apps/back/src/modules/customers/customers.module.ts
- apps/back/src/modules/customers/customers.service.ts
- apps/back/src/modules/employees/employees.controller.ts
- apps/back/src/modules/employees/employees.module.ts
- apps/back/src/modules/images/images.controller.ts
- apps/back/src/modules/images/images.module.ts
- apps/back/src/modules/images/images.service.ts
- apps/back/src/types/images/image-token.type.ts
- apps/back/src/types/images/image-typed.type.ts
- apps/back/src/types/images/index.ts
- packages/common/src/dtos/images/get-image.dto.ts
- packages/common/src/dtos/images/index.ts
- packages/common/src/dtos/index.ts
I added a system that allow any people that have a valid link to make requests on `/images/{token}` in order to get image described by the given token.
> SEM-52 & SEM-55 - Create route to get images via tokens

- apps/back/Dockerfile
- apps/front/Dockerfile
- docker-compose.yml
- package-lock.json
- Add commands to docker-compose to install at start to avoid a global build everytime
- Add package-lock to Dockerfile
> SEM-62 - Update docker compose and dockerfile to improve build time

- apps/back/prisma/migrations/20240906122332_unique_locations/migration.sql
- apps/back/prisma/schema.prisma
- apps/back/src/modules/customers/customers-migration.service.ts
- apps/back/src/modules/customers/customers.module.ts
- apps/back/src/modules/employees/employees-migration.service.ts
- apps/back/src/modules/statistics/statistics-migration.service.ts
- apps/back/src/modules/statistics/statistics.controller.ts
- apps/back/src/modules/statistics/statistics.module.ts
I synced events, customers, employees and meetings before computing statistics.
Initial loading time: ~ 3m15s
Avg. loading time: >1s
> SEM-61 Add statistics migration

- apps/back/prisma/seed.ts
- apps/back/src/modules/customers/customers-migration.service.ts
- apps/back/src/modules/customers/customers.service.ts
- apps/back/src/providers/legacy-api/legacy-api-convertors.ts
- apps/back/src/types/legacy-api/dtos/index.ts
- apps/back/src/types/legacy-api/payment-method.type.ts
- apps/front/src/components/customers/encounters/columns.tsx
- apps/front/src/components/customers/payments/columns.tsx
I added payment migration which enabled payment methods listing in users' dtos. With this implemented I spotted a bug in the front when customers' reimbursement was displaying double negative signs.
Also @TekMath I saw your 'squares' in encounters were a bit "squished" which I though was not the intended behavior ^^.
Before:
After:
> SEM-26 Customer payment methods

- apps/front/package.json
- apps/front/src/api/customers/delete.ts
- apps/front/src/api/customers/index.ts
- apps/front/src/app/customers/page.tsx
- apps/front/src/components/customers/table/actions.tsx
- apps/front/src/components/customers/table/index.tsx
- apps/front/src/components/ui/alert-dialog.tsx
- package-lock.json
We now can delete customers from the table with the bulk action button
> Delete customers from table

- apps/front/src/api/employees/delete.ts
- apps/front/src/api/employees/index.ts
- apps/front/src/app/coaches/page.tsx
- apps/front/src/components/coaches/table/actions.tsx
- apps/front/src/components/coaches/table/index.tsx
I added ability to delete coaches from table.
> SEM-71 - Delete coaches from table

- apps/front/src/app/coaches/page.tsx
- apps/front/src/app/customers/page.tsx
- apps/front/src/components/coaches/table/index.tsx
- apps/front/src/components/customers/table/index.tsx
- apps/front/src/components/table/select/filters.tsx
- apps/front/src/components/table/select/index.tsx
- packages/common/src/dtos/customers/get-customers.dto.ts
- packages/common/src/dtos/employees/get-employees.dto.ts
I fixed customers and coaches search by email. Hope the client like it !
> SEM-77 - Fix customers and coaches search

- apps/back/src/app/app.module.ts
- apps/back/src/modules/tips/tips-migration.service.ts
- apps/back/src/modules/tips/tips.controller.ts
- apps/back/src/modules/tips/tips.module.ts
- apps/back/src/modules/tips/tips.service.ts
- apps/back/src/types/tips/candidate.ts
- apps/back/src/types/tips/index.ts
- apps/front/src/api/index.ts
- apps/front/src/api/tips/get.ts
- apps/front/src/api/tips/index.ts
- apps/front/src/api/tips/list.ts
- apps/front/src/app/tips/page.tsx
- packages/common/src/dtos/index.ts
- packages/common/src/dtos/tips/get-tips.dto.ts
- packages/common/src/dtos/tips/index.ts
- packages/common/src/dtos/tips/patch-tip.dto.ts
- packages/common/src/dtos/tips/post-create-tip.dto.ts
I added the tips module with its migration service. 
The front has also been updated to retrieve tips.
> SEM-82 Tips module

- apps/back/src/modules/customers/customers.controller.ts
This pull-request updates the customer creation process assigning the created customer to the coach that made the request. However, the old behavior has been kept for managers.
> SEM-84 Assign customers on creation

- apps/front/src/app/customers/[id]/page.tsx
- apps/front/src/components/customers/profile.tsx
I added a link on customer profile to go to its coach profile.
> SEM-81 - Add link to coach profile in customer profile

- apps/back/src/modules/tips/tips.controller.ts
- apps/front/src/api/tips/delete.ts
- apps/front/src/api/tips/index.ts
- apps/front/src/app/coaches/page.tsx
- apps/front/src/app/customers/[id]/closet/page.tsx
- apps/front/src/app/tips/page.tsx
- apps/front/src/components/dashboard/charts/metrics.tsx
- packages/common/src/dtos/tips/delete-tip.dto.ts
- packages/common/src/dtos/tips/index.ts
- packages/common/src/dtos/tips/patch-tip.dto.ts
> SEM-85 - Tasks delete create

- apps/back/prisma/seed.ts
- apps/back/src/modules/statistics/statistics.service.ts
- apps/front/src/app/auth/login/page.tsx
- package-lock.json
I added a forgot password link in login page. By the way, I also updated some terrible work made by terrible people in back statistics service.
> SEM-91 - Add forgot password link
